### ISSUE TITLE
Also give the output color in hex

### ISSUE THREAD

**Issue by nltesown** [tylergaw/colorme#9]
This is a very nice app and I'm sure to use it a lot... especially if you also give the output color's hexadecimal code (when no alpha is involved). Thanks!

**Comment by tylergaw** [comment]
Thanks @nltesown. Right there with you. I'm working on that change–plus others–in https://github.com/tylergaw/colorme/pull/8 Hope to have it out tonight.

**Comment by tylergaw** [comment]
Hey @nltesown I got the format option added to the UI in #8 and released it a few minutes ago: https://colorme.io
